### ISSUE TITLE
Pre-launch checklist

### ISSUE THREAD

**Issue by treeder** [iron-io/functions#276]
* [x] Bump versions to 0.1.0 (alpha version)
* [x] Ensure fnctl installer works
* [x] Create an fnctl dns entry and enable ssl installs of the cli tool
* [x] Ensure broken images in docs work after going public
* [x] Update and push new swagger to swaggerhub, make sure it matches api. 
* [x] Change client generation to use the public swagger URL 
* [x] Regenerate clients

**Comment by treeder** [comment]
Created a separate issue for dns/ssh install. #304
